### ISSUE TITLE
archive mods with constituents

### ISSUE THREAD

**Issue by balmas** [PerseusDL/cite_collections_rails#15]
currently, when we process a mods file with constituent records, we record an error if the parent mods file doesn't contain any identifier, even when all the constituent records are parsed successfully. This leaves the mods file in catalog_pending to be reprocessed and would likely result in duplicates records being created on the next run of the update. (I'm not positive if this was always the case, or has been exacerbated by my recent changes)

We should probably only process a mods file with consitutent records if ALL of the constituents are processed successfully.  Processing the parent mods file should be optional.

**Comment by AlisonBabeu** [comment]
The only potential challenge with this approach is that sometimes a few constituents in a large volume might not process successfully simply due to the lack of identifier unless perhaps its time to create a null identifier of some sort to indicate this without throwing an error?

**Comment by balmas** [comment]
Well in that case I guess maybe the approach is just the keep the split records that don't parse. They are kept separately now so I think then it's just a change to not keepnthe parent mods if it doesn't have one.
